@echo off
REM ****************************************************************************
REM Vivado (TM) v2022.2 (64-bit)
REM
REM Filename    : simulate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for simulating the design by launching the simulator
REM
REM Generated by Vivado on Thu Mar 23 09:08:24 -0400 2023
REM SW Build 3671981 on Fri Oct 14 05:00:03 MDT 2022
REM
REM IP Build 3669848 on Fri Oct 14 08:30:02 MDT 2022
REM
REM usage: simulate.bat
REM
REM ****************************************************************************
REM simulate design
echo "xsim RS32I_Testbench_behav -key {Behavioral:sim_1:Functional:RS32I_Testbench} -tclbatch RS32I_Testbench.tcl -view C:/Users/T5810/Documents/ONEDRIVE/Documents/Projects/Personal FPGA Projects/RV32I_VHDL_A02/RS32I_Testbench_behav.wcfg -log simulate.log"
call xsim  RS32I_Testbench_behav -key {Behavioral:sim_1:Functional:RS32I_Testbench} -tclbatch RS32I_Testbench.tcl -view C:/Users/T5810/Documents/ONEDRIVE/Documents/Projects/Personal FPGA Projects/RV32I_VHDL_A02/RS32I_Testbench_behav.wcfg -log simulate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
